drop database QL_BAN_HANG
create database QL_BAN_HANG
use QL_BAN_HANG

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_BARCODE_NHAN_VIEN]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [BARCODE] DROP CONSTRAINT [FK_BARCODE_NHAN_VIEN]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_BARCODE_SAN_PHAM]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [BARCODE] DROP CONSTRAINT [FK_BARCODE_SAN_PHAM]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_CTHDDH_HDBH]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [CT_HD_BAN_HANG] DROP CONSTRAINT [FK_CTHDDH_HDBH]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_CTHDDH_SanPham]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [CT_HD_BAN_HANG] DROP CONSTRAINT [FK_CTHDDH_SanPham]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_CT_PHIEU_KT_PHIEU_KIEM_TRA]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [CT_PHIEU_KT] DROP CONSTRAINT [FK_CT_PHIEU_KT_PHIEU_KIEM_TRA]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_CT_PHIEU_KT_SAN_PHAM]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [CT_PHIEU_KT] DROP CONSTRAINT [FK_CT_PHIEU_KT_SAN_PHAM]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_Chi_Tiet_Phieu_Mua_Hang_Phieu_Mua_Hang]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [CT_PHIEU_MUA_HANG] DROP CONSTRAINT [FK_Chi_Tiet_Phieu_Mua_Hang_Phieu_Mua_Hang]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_CT_PHIEU_MUA_HANG_SAN_PHAM]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [CT_PHIEU_MUA_HANG] DROP CONSTRAINT [FK_CT_PHIEU_MUA_HANG_SAN_PHAM]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_CT_PHIEU_NHAP_KHO_PHIEU_NHAP_KHO]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [CT_PHIEU_NHAP_KHO] DROP CONSTRAINT [FK_CT_PHIEU_NHAP_KHO_PHIEU_NHAP_KHO]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_CT_PHIEU_NHAP_KHO_SAN_PHAM]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [CT_PHIEU_NHAP_KHO] DROP CONSTRAINT [FK_CT_PHIEU_NHAP_KHO_SAN_PHAM]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_CT_PHIEU_XUAT_KHO_PHIEU_XUAT_KHO]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [CT_PHIEU_XUAT_KHO] DROP CONSTRAINT [FK_CT_PHIEU_XUAT_KHO_PHIEU_XUAT_KHO]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_CT_PHIEU_XUAT_KHO_SAN_PHAM]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [CT_PHIEU_XUAT_KHO] DROP CONSTRAINT [FK_CT_PHIEU_XUAT_KHO_SAN_PHAM]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_CT_PHIEU_YC_NHAP_KHO_SAN_PHAM]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [CT_PHIEU_YC_NHAP_KHO] DROP CONSTRAINT [FK_CT_PHIEU_YC_NHAP_KHO_SAN_PHAM]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_CT_PHIEU_YC_NHAP_KHO_SAN_PHAM_02]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [CT_PHIEU_YC_NHAP_KHO] DROP CONSTRAINT [FK_CT_PHIEU_YC_NHAP_KHO_SAN_PHAM_02]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_CTPYCNK_Phieu_Yeu_Cau_Nhap_Kho]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [CT_PHIEU_YC_NHAP_KHO] DROP CONSTRAINT [FK_CTPYCNK_Phieu_Yeu_Cau_Nhap_Kho]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_CT_PHIEU_YC_XUAT_KHO_PHIEU_YC_XUAT_KHO]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [CT_PHIEU_YC_XUAT_KHO] DROP CONSTRAINT [FK_CT_PHIEU_YC_XUAT_KHO_PHIEU_YC_XUAT_KHO]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_CT_PHIEU_YC_XUAT_KHO_SAN_PHAM]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [CT_PHIEU_YC_XUAT_KHO] DROP CONSTRAINT [FK_CT_PHIEU_YC_XUAT_KHO_SAN_PHAM]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_HDBH_NhanVien]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [HD_BAN_HANG] DROP CONSTRAINT [FK_HDBH_NhanVien]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_NhanVien_CHUC_VU]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [NHAN_VIEN] DROP CONSTRAINT [FK_NhanVien_CHUC_VU]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_NhanVien_PHONG_BAN]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [NHAN_VIEN] DROP CONSTRAINT [FK_NhanVien_PHONG_BAN]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_PHIEU_KIEM_TRA_KHO]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [PHIEU_KIEM_TRA] DROP CONSTRAINT [FK_PHIEU_KIEM_TRA_KHO]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_PHIEU_KIEM_TRA_NHAN_VIEN]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [PHIEU_KIEM_TRA] DROP CONSTRAINT [FK_PHIEU_KIEM_TRA_NHAN_VIEN]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_PHIEU_MUA_HANG_NHA_CUNG_CAP]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [PHIEU_MUA_HANG] DROP CONSTRAINT [FK_PHIEU_MUA_HANG_NHA_CUNG_CAP]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_PHIEU_MUA_HANG_NHAN_VIEN]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [PHIEU_MUA_HANG] DROP CONSTRAINT [FK_PHIEU_MUA_HANG_NHAN_VIEN]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_PHIEU_NHAP_KHO_KHO]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [PHIEU_NHAP_KHO] DROP CONSTRAINT [FK_PHIEU_NHAP_KHO_KHO]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_PHIEU_NHAP_KHO_NHAN_VIEN]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [PHIEU_NHAP_KHO] DROP CONSTRAINT [FK_PHIEU_NHAP_KHO_NHAN_VIEN]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_PHIEU_NHAP_KHO_Phieu_Yeu_Cau_Nhap_Kho]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [PHIEU_NHAP_KHO] DROP CONSTRAINT [FK_PHIEU_NHAP_KHO_Phieu_Yeu_Cau_Nhap_Kho]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_PHIEU_XUAT_KHO_CUA_HANG]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [PHIEU_XUAT_KHO] DROP CONSTRAINT [FK_PHIEU_XUAT_KHO_CUA_HANG]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_PHIEU_XUAT_KHO_NHAN_VIEN]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [PHIEU_XUAT_KHO] DROP CONSTRAINT [FK_PHIEU_XUAT_KHO_NHAN_VIEN]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_PHIEU_XUAT_KHO_PHIEU_YC_XUAT_KHO]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [PHIEU_XUAT_KHO] DROP CONSTRAINT [FK_PHIEU_XUAT_KHO_PHIEU_YC_XUAT_KHO]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_PHIEU_YC_NHAP_KHO_NHAN_VIEN]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [PHIEU_YC_NHAP_KHO] DROP CONSTRAINT [FK_PHIEU_YC_NHAP_KHO_NHAN_VIEN]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_Phieu_Yeu_Cau_Nhap_Kho_Phieu_Mua_Hang]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [PHIEU_YC_NHAP_KHO] DROP CONSTRAINT [FK_Phieu_Yeu_Cau_Nhap_Kho_Phieu_Mua_Hang]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_PHIEU_YC_XUAT_KHO_KHO]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [PHIEU_YC_XUAT_KHO] DROP CONSTRAINT [FK_PHIEU_YC_XUAT_KHO_KHO]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_PHIEU_YC_XUAT_KHO_NHAN_VIEN]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [PHIEU_YC_XUAT_KHO] DROP CONSTRAINT [FK_PHIEU_YC_XUAT_KHO_NHAN_VIEN]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[BARCODE]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [BARCODE]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[CHUC_VU]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [CHUC_VU]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[CT_HD_BAN_HANG]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [CT_HD_BAN_HANG]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[CT_PHIEU_KT]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [CT_PHIEU_KT]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[CT_PHIEU_MUA_HANG]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [CT_PHIEU_MUA_HANG]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[CT_PHIEU_NHAP_KHO]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [CT_PHIEU_NHAP_KHO]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[CT_PHIEU_XUAT_KHO]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [CT_PHIEU_XUAT_KHO]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[CT_PHIEU_YC_NHAP_KHO]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [CT_PHIEU_YC_NHAP_KHO]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[CT_PHIEU_YC_XUAT_KHO]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [CT_PHIEU_YC_XUAT_KHO]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[CUA_HANG]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [CUA_HANG]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[HD_BAN_HANG]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [HD_BAN_HANG]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[KHO]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [KHO]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[NHA_CUNG_CAP]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [NHA_CUNG_CAP]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[NHAN_VIEN]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [NHAN_VIEN]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[PHIEU_KIEM_TRA]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [PHIEU_KIEM_TRA]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[PHIEU_MUA_HANG]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [PHIEU_MUA_HANG]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[PHIEU_NHAP_KHO]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [PHIEU_NHAP_KHO]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[PHIEU_XUAT_KHO]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [PHIEU_XUAT_KHO]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[PHIEU_YC_NHAP_KHO]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [PHIEU_YC_NHAP_KHO]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[PHIEU_YC_XUAT_KHO]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [PHIEU_YC_XUAT_KHO]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[PHONG_BAN]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [PHONG_BAN]
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[SAN_PHAM]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [SAN_PHAM]
;

CREATE TABLE [BARCODE]
(
	[MaBarcode] binary(20) NOT NULL,
	[MaSP] varchar(10) NOT NULL,
	[MaNV] varchar(10) NOT NULL,
	[GhiChu] nvarchar(500),
	[TrangThai] int
)
;

CREATE TABLE [CHUC_VU]
(
	[MaCV] varchar(10) NOT NULL,
	[TenCV] nvarchar(200) NOT NULL,
	[GhiChu] nvarchar(500),
	[TrangThai] int
)
;

CREATE TABLE [CT_HD_BAN_HANG]
(
	[MaHD] varchar(10) NOT NULL,
	[MaSP] varchar(10),
	[SoLuong] int,
	[TongTien] int,
	[NgayLap] date,
	[TinhTrang] int
)
;

CREATE TABLE [CT_PHIEU_KT]
(
	[SoPhieu] varchar(10) NOT NULL,
	[MaSP] varchar(10) NOT NULL,
	[TenSP] nvarchar(200) NOT NULL,
	[MaNCC] varchar(10) NOT NULL,
	[TongSo] int NOT NULL,
	[HuHong] int NOT NULL,
	[NguyenNhan] nvarchar(200) NOT NULL,
	[GhiChu] nvarchar(500),
	[TrangThai] int
)
;

CREATE TABLE [CT_PHIEU_MUA_HANG]
(
	[SoPhieu] varchar(10) NOT NULL,
	[MaSP] varchar(10) NOT NULL,
	[TenSP] nvarchar(50) NOT NULL,
	[SoLuong] int NOT NULL,
	[GhiChu] nvarchar(500),
	[TrangThai] int
)
;

CREATE TABLE [CT_PHIEU_NHAP_KHO]
(
	[SoPhieu] varchar(10) NOT NULL,
	[MaSP] varchar(10) NOT NULL,
	[TenSP] nvarchar(50) NOT NULL,
	[SoLuong] int NOT NULL,
	[MaNCC] varchar(10) NOT NULL,
	[GhiChu] nvarchar(500),
	[TrangThai] int
)
;

CREATE TABLE [CT_PHIEU_XUAT_KHO]
(
	[SoPhieu] varchar(10) NOT NULL,
	[MaCuaHang] varchar(10) NOT NULL,
	[MaSP] varchar(10) NOT NULL,
	[TenSP] nvarchar(200) NOT NULL,
	[SoLuong] int NOT NULL,
	[MaNCC] varchar(10) NOT NULL,
	[NgayXuat] date NOT NULL,
	[GhiChu] nvarchar(500),
	[TrangThai] int
)
;

CREATE TABLE [CT_PHIEU_YC_NHAP_KHO]
(
	[SoPhieu] varchar(10) NOT NULL,
	[MaSP] varchar(10) NOT NULL,
	[TenSP] nvarchar(200) NOT NULL,
	[SL] int NOT NULL,
	[GhiChu] nvarchar(500),
	[TrangThai] int
)
;

CREATE TABLE [CT_PHIEU_YC_XUAT_KHO]
(
	[SoPhieu] varchar(10) NOT NULL,
	[MaCuaHang] varchar(10) NOT NULL,
	[MaSP] varchar(10) NOT NULL,
	[TenSP] nvarchar(200) NOT NULL,
	[SoLuong] int NOT NULL,
	[MaNCC] varchar(10) NOT NULL,
	[GhiChu] nvarchar(500),
	[TrangThai] int
)
;

CREATE TABLE [CUA_HANG]
(
	[MaCuaHang] varchar(10) NOT NULL,
	[TenCuaHang] nvarchar(200) NOT NULL,
	[DiaChi] nvarchar(200) NOT NULL,
	[SoDT] varchar(20) NOT NULL,
	[GhiChu] nvarchar(500),
	[TrangThai] int
)
;

CREATE TABLE [HD_BAN_HANG]
(
	[MaHD] varchar(10) NOT NULL,
	[MaNV] varchar(10) NOT NULL,
	[TongTien] int NOT NULL,
	[TinhTrang] varchar(50)
)
;

CREATE TABLE [KHO]
(
	[MaKho] varchar(10) NOT NULL,
	[TenKho] nvarchar(200) NOT NULL,
	[DiaChi] nvarchar(200) NOT NULL,
	[SoDT] varchar(20) NOT NULL,
	[GhiChu] nvarchar(500),
	[TrangThai] int
)
;

CREATE TABLE [NHA_CUNG_CAP]
(
	[MaNCC] varchar(10) NOT NULL,
	[TenNCC] nvarchar(200) NOT NULL,
	[DiaChi] nvarchar(200) NOT NULL,
	[SDT] int NOT NULL,
	[Email] varchar(50) NOT NULL,
	[NguoiDaiDien] varchar(50) NOT NULL,
	[GhiChu] nvarchar(500),
	[TrangThai] int
)
;

CREATE TABLE [NHAN_VIEN]
(
	[MaNV] varchar(10) NOT NULL,
	[TenNV] nvarchar(50) NOT NULL,
	[SDT] varchar(50) NOT NULL,
	[DiaChi] nvarchar(200) NOT NULL,
	[SoCMND] varchar(15) NOT NULL,
	[QueQuan] nvarchar(200) NOT NULL,
	[Email] varchar(50) NOT NULL,
	[MaCV] varchar(10) NOT NULL,
	[MaPB] varchar(10) NOT NULL,
	[GhiChu] nvarchar(500),
	[TrangThai] int
)
;

CREATE TABLE [PHIEU_KIEM_TRA]
(
	[SoPhieu] varchar(10) NOT NULL,
	[MaKho] varchar(10) NOT NULL,
	[MaNV] varchar(10) NOT NULL,
	[NgayKT] date NOT NULL,
	[GhiChu] nvarchar(500),
	[TrangThai] int
)
;

CREATE TABLE [PHIEU_MUA_HANG]
(
	[SoPhieu] varchar(10) NOT NULL,
	[MaNV] varchar(10) NOT NULL,
	[MaNCC] varchar(10) NOT NULL,
	[NgayLapPhieu] date NOT NULL,
	[GhiChu] nvarchar(500),
	[TrangThai] int
)
;

CREATE TABLE [PHIEU_NHAP_KHO]
(
	[SoPhieu] varchar(10) NOT NULL,
	[MaNV] varchar(10) NOT NULL,
	[MaKho] varchar(10) NOT NULL,
	[NgayLap] date NOT NULL,
	[GhiChu] nvarchar(500),
	[TrangThai] int
)
;

CREATE TABLE [PHIEU_XUAT_KHO]
(
	[SoPhieu] varchar(10) NOT NULL,
	[MaNV] varchar(10) NOT NULL,
	[MaCuaHang] varchar(10) NOT NULL,
	[NgayLap] date NOT NULL,
	[GhiChu] varchar(500) NOT NULL,
	[TrangThai] int
)
;

CREATE TABLE [PHIEU_YC_NHAP_KHO]
(
	[SoPhieu] varchar(10) NOT NULL,
	[MaNV] varchar(10) NOT NULL,
	[MaKho] varchar(10) NOT NULL,
	[NgayLap] date NOT NULL,
	[GhiChu] nvarchar(500),
	[TrangThai] int
)
;

CREATE TABLE [PHIEU_YC_XUAT_KHO]
(
	[SoPhieu] varchar(10) NOT NULL,
	[MaNV] varchar(10) NOT NULL,
	[MaKho] varchar(10) NOT NULL,
	[NgayLap] date NOT NULL,
	[GhiChu] nvarchar(500),
	[TinhTrang] int
)
;

CREATE TABLE [PHONG_BAN]
(
	[MaPB] varchar(10) NOT NULL,
	[TenPB] nvarchar(200) NOT NULL,
	[GhiChu] nvarchar(500),
	[TrangThai] int
)
;

CREATE TABLE [SAN_PHAM]
(
	[MaSP] varchar(10) NOT NULL,
	[TenSP] nvarchar(50),
	[MaBarcode] varchar(50) NOT NULL,
	[SoLuong] int,
	[MaNCC] int,
	[NhaSX] nvarchar(200) NOT NULL,
	[NgaySX] date NOT NULL,
	[HanSuDung] int NOT NULL,
	[HinhAnh] varchar(50),
	[TinhTrang] int
)
;

CREATE INDEX [IXFK_BARCODE_NHAN_VIEN] 
 ON [BARCODE] ([MaNV] ASC)
;

CREATE INDEX [IXFK_BARCODE_SAN_PHAM] 
 ON [BARCODE] ([MaSP] ASC)
;

ALTER TABLE [BARCODE] 
 ADD CONSTRAINT [PK_BARCODE]
	PRIMARY KEY CLUSTERED ([MaBarcode])
;

ALTER TABLE [CHUC_VU] 
 ADD CONSTRAINT [PK_CHUC_VU]
	PRIMARY KEY CLUSTERED ([MaCV])
;

CREATE INDEX [IXFK_CTHDDH_HDBH] 
 ON [CT_HD_BAN_HANG] ([MaHD] ASC)
;

CREATE INDEX [IXFK_CTHDDH_SanPham] 
 ON [CT_HD_BAN_HANG] ([MaSP] ASC)
;

ALTER TABLE [CT_HD_BAN_HANG] 
 ADD CONSTRAINT [PK_CTHDDH]
	PRIMARY KEY CLUSTERED ([MaHD])
;

CREATE INDEX [IXFK_CT_PHIEU_KT_PHIEU_KIEM_TRA] 
 ON [CT_PHIEU_KT] ([SoPhieu] ASC)
;

CREATE INDEX [IXFK_CT_PHIEU_KT_SAN_PHAM] 
 ON [CT_PHIEU_KT] ([MaSP] ASC)
;

CREATE INDEX [IXFK_CT_PHIEU_KT_SAN_PHAM_02] 
 ON [CT_PHIEU_KT] ([MaSP] ASC)
;

ALTER TABLE [CT_PHIEU_KT] 
 ADD CONSTRAINT [PK_CT_PHIEU_KT]
	PRIMARY KEY CLUSTERED ([SoPhieu],[MaSP])
;

CREATE INDEX [IXFK_Chi_Tiet_Phieu_Mua_Hang_Phieu_Mua_Hang] 
 ON [CT_PHIEU_MUA_HANG] ([SoPhieu] ASC)
;

CREATE INDEX [IXFK_CT_PHIEU_MUA_HANG_SAN_PHAM] 
 ON [CT_PHIEU_MUA_HANG] ([MaSP] ASC)
;

CREATE INDEX [IXFK_CT_PHIEU_MUA_HANG_SAN_PHAM_02] 
 ON [CT_PHIEU_MUA_HANG] ([MaSP] ASC)
;

ALTER TABLE [CT_PHIEU_MUA_HANG] 
 ADD CONSTRAINT [PK_Chi_Tiet_Phieu_Mua_Hang]
	PRIMARY KEY CLUSTERED ([SoPhieu],[MaSP])
;

CREATE INDEX [IXFK_CT_PHIEU_NHAP_KHO_PHIEU_NHAP_KHO] 
 ON [CT_PHIEU_NHAP_KHO] ([SoPhieu] ASC)
;

CREATE INDEX [IXFK_CT_PHIEU_NHAP_KHO_SAN_PHAM] 
 ON [CT_PHIEU_NHAP_KHO] ([MaSP] ASC)
;

CREATE INDEX [IXFK_CT_PHIEU_NHAP_KHO_SAN_PHAM_02] 
 ON [CT_PHIEU_NHAP_KHO] ([MaSP] ASC)
;

ALTER TABLE [CT_PHIEU_NHAP_KHO] 
 ADD CONSTRAINT [PK_CT_PHIEU_NHAP_KHO]
	PRIMARY KEY CLUSTERED ([SoPhieu],[MaSP])
;

CREATE INDEX [IXFK_CT_PHIEU_XUAT_KHO_CUA_HANG] 
 ON [CT_PHIEU_XUAT_KHO] ([MaCuaHang] ASC)
;

CREATE INDEX [IXFK_CT_PHIEU_XUAT_KHO_PHIEU_XUAT_KHO] 
 ON [CT_PHIEU_XUAT_KHO] ([SoPhieu] ASC)
;

CREATE INDEX [IXFK_CT_PHIEU_XUAT_KHO_SAN_PHAM] 
 ON [CT_PHIEU_XUAT_KHO] ([MaSP] ASC)
;

CREATE INDEX [IXFK_CT_PHIEU_XUAT_KHO_SAN_PHAM_02] 
 ON [CT_PHIEU_XUAT_KHO] ([MaSP] ASC)
;

ALTER TABLE [CT_PHIEU_XUAT_KHO] 
 ADD CONSTRAINT [PK_CT_PHIEU_XUAT_KHO]
	PRIMARY KEY CLUSTERED ([SoPhieu],[MaCuaHang],[MaSP])
;

CREATE INDEX [IXFK_CT_PHIEU_YC_NHAP_KHO_SAN_PHAM] 
 ON [CT_PHIEU_YC_NHAP_KHO] ([MaSP] ASC)
;

ALTER TABLE [CT_PHIEU_YC_NHAP_KHO] 
 ADD CONSTRAINT [PK_CTPYCNK]
	PRIMARY KEY CLUSTERED ([SoPhieu],[MaSP])
;

CREATE INDEX [IXFK_CT_PHIEU_YC_XUAT_KHO_PHIEU_YC_XUAT_KHO] 
 ON [CT_PHIEU_YC_XUAT_KHO] ([SoPhieu] ASC)
;

CREATE INDEX [IXFK_CT_PHIEU_YC_XUAT_KHO_SAN_PHAM] 
 ON [CT_PHIEU_YC_XUAT_KHO] ([MaSP] ASC)
;

ALTER TABLE [CT_PHIEU_YC_XUAT_KHO] 
 ADD CONSTRAINT [PK_CT_PHIEU_YC_XUAT_KHO]
	PRIMARY KEY CLUSTERED ([SoPhieu])
;

ALTER TABLE [CUA_HANG] 
 ADD CONSTRAINT [PK_CUA_HANG]
	PRIMARY KEY CLUSTERED ([MaCuaHang])
;

CREATE INDEX [IXFK_HDBH_NhanVien] 
 ON [HD_BAN_HANG] ([MaNV] ASC)
;

ALTER TABLE [HD_BAN_HANG] 
 ADD CONSTRAINT [PK_HDBH]
	PRIMARY KEY CLUSTERED ([MaHD])
;

ALTER TABLE [KHO] 
 ADD CONSTRAINT [PK_KHO]
	PRIMARY KEY CLUSTERED ([MaKho])
;

ALTER TABLE [NHA_CUNG_CAP] 
 ADD CONSTRAINT [PK_Nha_Cung_Cap]
	PRIMARY KEY CLUSTERED ([MaNCC])
;

CREATE INDEX [IXFK_NhanVien_CHUC_VU] 
 ON [NHAN_VIEN] ([MaCV] ASC)
;

CREATE INDEX [IXFK_NhanVien_PHONG_BAN] 
 ON [NHAN_VIEN] ([MaPB] ASC)
;

ALTER TABLE [NHAN_VIEN] 
 ADD CONSTRAINT [PK_NhanVien]
	PRIMARY KEY CLUSTERED ([MaNV])
;

CREATE INDEX [IXFK_PHIEU_KIEM_TRA_KHO] 
 ON [PHIEU_KIEM_TRA] ([MaKho] ASC)
;

CREATE INDEX [IXFK_PHIEU_KIEM_TRA_NHAN_VIEN] 
 ON [PHIEU_KIEM_TRA] ([MaNV] ASC)
;

ALTER TABLE [PHIEU_KIEM_TRA] 
 ADD CONSTRAINT [PK_PHIEU_KIEM_TRA]
	PRIMARY KEY CLUSTERED ([SoPhieu])
;

CREATE INDEX [IXFK_PHIEU_MUA_HANG_NHA_CUNG_CAP] 
 ON [PHIEU_MUA_HANG] ([MaNCC] ASC)
;

CREATE INDEX [IXFK_PHIEU_MUA_HANG_NHAN_VIEN] 
 ON [PHIEU_MUA_HANG] ([MaNV] ASC)
;

ALTER TABLE [PHIEU_MUA_HANG] 
 ADD CONSTRAINT [PK_Phieu_Mua_Hang]
	PRIMARY KEY CLUSTERED ([SoPhieu])
;

CREATE INDEX [IXFK_PHIEU_NHAP_KHO_KHO] 
 ON [PHIEU_NHAP_KHO] ([MaKho] ASC)
;

CREATE INDEX [IXFK_PHIEU_NHAP_KHO_NHAN_VIEN] 
 ON [PHIEU_NHAP_KHO] ([MaNV] ASC)
;

CREATE INDEX [IXFK_PHIEU_NHAP_KHO_Phieu_Yeu_Cau_Nhap_Kho] 
 ON [PHIEU_NHAP_KHO] ([SoPhieu] ASC)
;

ALTER TABLE [PHIEU_NHAP_KHO] 
 ADD CONSTRAINT [PK_PHIEU_YC_NHAP_KHO]
	PRIMARY KEY CLUSTERED ([SoPhieu])
;

CREATE INDEX [IXFK_PHIEU_XUAT_KHO_CUA_HANG] 
 ON [PHIEU_XUAT_KHO] ([MaCuaHang] ASC)
;

CREATE INDEX [IXFK_PHIEU_XUAT_KHO_NHAN_VIEN] 
 ON [PHIEU_XUAT_KHO] ([MaNV] ASC)
;

CREATE INDEX [IXFK_PHIEU_XUAT_KHO_PHIEU_YC_XUAT_KHO] 
 ON [PHIEU_XUAT_KHO] ([SoPhieu] ASC)
;

ALTER TABLE [PHIEU_XUAT_KHO] 
 ADD CONSTRAINT [PK_PHIEU_XUAT_KHO]
	PRIMARY KEY CLUSTERED ([SoPhieu])
;

CREATE INDEX [IXFK_PHIEU_YC_NHAP_KHO_NHAN_VIEN] 
 ON [PHIEU_YC_NHAP_KHO] ([MaNV] ASC)
;

CREATE INDEX [IXFK_Phieu_Yeu_Cau_Nhap_Kho_Phieu_Mua_Hang] 
 ON [PHIEU_YC_NHAP_KHO] ([SoPhieu] ASC)
;

ALTER TABLE [PHIEU_YC_NHAP_KHO] 
 ADD CONSTRAINT [PK_Phieu_Yeu_Cau_Nhap_Kho]
	PRIMARY KEY CLUSTERED ([SoPhieu])
;

CREATE INDEX [IXFK_PHIEU_YC_XUAT_KHO_KHO] 
 ON [PHIEU_YC_XUAT_KHO] ([MaKho] ASC)
;

CREATE INDEX [IXFK_PHIEU_YC_XUAT_KHO_NHAN_VIEN] 
 ON [PHIEU_YC_XUAT_KHO] ([MaNV] ASC)
;

ALTER TABLE [PHIEU_YC_XUAT_KHO] 
 ADD CONSTRAINT [PK_PHIEU_YC_XUAT_KHO]
	PRIMARY KEY CLUSTERED ([SoPhieu])
;

ALTER TABLE [PHONG_BAN] 
 ADD CONSTRAINT [PK_PHONG_BAN]
	PRIMARY KEY CLUSTERED ([MaPB])
;

ALTER TABLE [SAN_PHAM] 
 ADD CONSTRAINT [PK_SanPham]
	PRIMARY KEY CLUSTERED ([MaSP])
;

ALTER TABLE [BARCODE] ADD CONSTRAINT [FK_BARCODE_NHAN_VIEN]
	FOREIGN KEY ([MaNV]) REFERENCES [NHAN_VIEN] ([MaNV])
;

ALTER TABLE [BARCODE] ADD CONSTRAINT [FK_BARCODE_SAN_PHAM]
	FOREIGN KEY ([MaSP]) REFERENCES [SAN_PHAM] ([MaSP]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [CT_HD_BAN_HANG] ADD CONSTRAINT [FK_CTHDDH_HDBH]
	FOREIGN KEY ([MaHD]) REFERENCES [HD_BAN_HANG] ([MaHD]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [CT_HD_BAN_HANG] ADD CONSTRAINT [FK_CTHDDH_SanPham]
	FOREIGN KEY ([MaSP]) REFERENCES [SAN_PHAM] ([MaSP]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [CT_PHIEU_KT] ADD CONSTRAINT [FK_CT_PHIEU_KT_PHIEU_KIEM_TRA]
	FOREIGN KEY ([SoPhieu]) REFERENCES [PHIEU_KIEM_TRA] ([SoPhieu]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [CT_PHIEU_KT] ADD CONSTRAINT [FK_CT_PHIEU_KT_SAN_PHAM]
	FOREIGN KEY ([MaSP]) REFERENCES [SAN_PHAM] ([MaSP]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [CT_PHIEU_MUA_HANG] ADD CONSTRAINT [FK_Chi_Tiet_Phieu_Mua_Hang_Phieu_Mua_Hang]
	FOREIGN KEY ([SoPhieu]) REFERENCES [PHIEU_MUA_HANG] ([SoPhieu]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [CT_PHIEU_MUA_HANG] ADD CONSTRAINT [FK_CT_PHIEU_MUA_HANG_SAN_PHAM]
	FOREIGN KEY ([MaSP]) REFERENCES [SAN_PHAM] ([MaSP]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [CT_PHIEU_NHAP_KHO] ADD CONSTRAINT [FK_CT_PHIEU_NHAP_KHO_PHIEU_NHAP_KHO]
	FOREIGN KEY ([SoPhieu]) REFERENCES [PHIEU_NHAP_KHO] ([SoPhieu]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [CT_PHIEU_NHAP_KHO] ADD CONSTRAINT [FK_CT_PHIEU_NHAP_KHO_SAN_PHAM]
	FOREIGN KEY ([MaSP]) REFERENCES [SAN_PHAM] ([MaSP]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [CT_PHIEU_XUAT_KHO] ADD CONSTRAINT [FK_CT_PHIEU_XUAT_KHO_PHIEU_XUAT_KHO]
	FOREIGN KEY ([SoPhieu]) REFERENCES [PHIEU_XUAT_KHO] ([SoPhieu]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [CT_PHIEU_XUAT_KHO] ADD CONSTRAINT [FK_CT_PHIEU_XUAT_KHO_SAN_PHAM]
	FOREIGN KEY ([MaSP]) REFERENCES [SAN_PHAM] ([MaSP]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [CT_PHIEU_YC_NHAP_KHO] ADD CONSTRAINT [FK_CT_PHIEU_YC_NHAP_KHO_SAN_PHAM_02]
	FOREIGN KEY ([MaSP]) REFERENCES [SAN_PHAM] ([MaSP]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [CT_PHIEU_YC_NHAP_KHO] ADD CONSTRAINT [FK_CTPYCNK_Phieu_Yeu_Cau_Nhap_Kho]
	FOREIGN KEY ([SoPhieu]) REFERENCES [PHIEU_YC_NHAP_KHO] ([SoPhieu]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [CT_PHIEU_YC_XUAT_KHO] ADD CONSTRAINT [FK_CT_PHIEU_YC_XUAT_KHO_PHIEU_YC_XUAT_KHO]
	FOREIGN KEY ([SoPhieu]) REFERENCES [PHIEU_YC_XUAT_KHO] ([SoPhieu]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [CT_PHIEU_YC_XUAT_KHO] ADD CONSTRAINT [FK_CT_PHIEU_YC_XUAT_KHO_SAN_PHAM]
	FOREIGN KEY ([MaSP]) REFERENCES [SAN_PHAM] ([MaSP]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [HD_BAN_HANG] ADD CONSTRAINT [FK_HDBH_NhanVien]
	FOREIGN KEY ([MaNV]) REFERENCES [NHAN_VIEN] ([MaNV]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [NHAN_VIEN] ADD CONSTRAINT [FK_NhanVien_CHUC_VU]
	FOREIGN KEY ([MaCV]) REFERENCES [CHUC_VU] ([MaCV]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [NHAN_VIEN] ADD CONSTRAINT [FK_NhanVien_PHONG_BAN]
	FOREIGN KEY ([MaPB]) REFERENCES [PHONG_BAN] ([MaPB]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [PHIEU_KIEM_TRA] ADD CONSTRAINT [FK_PHIEU_KIEM_TRA_KHO]
	FOREIGN KEY ([MaKho]) REFERENCES [KHO] ([MaKho]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [PHIEU_KIEM_TRA] ADD CONSTRAINT [FK_PHIEU_KIEM_TRA_NHAN_VIEN]
	FOREIGN KEY ([MaNV]) REFERENCES [NHAN_VIEN] ([MaNV]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [PHIEU_MUA_HANG] ADD CONSTRAINT [FK_PHIEU_MUA_HANG_NHA_CUNG_CAP]
	FOREIGN KEY ([MaNCC]) REFERENCES [NHA_CUNG_CAP] ([MaNCC]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [PHIEU_MUA_HANG] ADD CONSTRAINT [FK_PHIEU_MUA_HANG_NHAN_VIEN]
	FOREIGN KEY ([MaNV]) REFERENCES [NHAN_VIEN] ([MaNV]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [PHIEU_NHAP_KHO] ADD CONSTRAINT [FK_PHIEU_NHAP_KHO_KHO]
	FOREIGN KEY ([MaKho]) REFERENCES [KHO] ([MaKho]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [PHIEU_NHAP_KHO] ADD CONSTRAINT [FK_PHIEU_NHAP_KHO_NHAN_VIEN]
	FOREIGN KEY ([MaNV]) REFERENCES [NHAN_VIEN] ([MaNV]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [PHIEU_NHAP_KHO] ADD CONSTRAINT [FK_PHIEU_NHAP_KHO_Phieu_Yeu_Cau_Nhap_Kho]
	FOREIGN KEY ([SoPhieu]) REFERENCES [PHIEU_YC_NHAP_KHO] ([SoPhieu]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [PHIEU_XUAT_KHO] ADD CONSTRAINT [FK_PHIEU_XUAT_KHO_CUA_HANG]
	FOREIGN KEY ([MaCuaHang]) REFERENCES [CUA_HANG] ([MaCuaHang]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [PHIEU_XUAT_KHO] ADD CONSTRAINT [FK_PHIEU_XUAT_KHO_NHAN_VIEN]
	FOREIGN KEY ([MaNV]) REFERENCES [NHAN_VIEN] ([MaNV]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [PHIEU_XUAT_KHO] ADD CONSTRAINT [FK_PHIEU_XUAT_KHO_PHIEU_YC_XUAT_KHO]
	FOREIGN KEY ([SoPhieu]) REFERENCES [PHIEU_YC_XUAT_KHO] ([SoPhieu]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [PHIEU_YC_NHAP_KHO] ADD CONSTRAINT [FK_PHIEU_YC_NHAP_KHO_NHAN_VIEN]
	FOREIGN KEY ([MaNV]) REFERENCES [NHAN_VIEN] ([MaNV]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [PHIEU_YC_NHAP_KHO] ADD CONSTRAINT [FK_Phieu_Yeu_Cau_Nhap_Kho_Phieu_Mua_Hang]
	FOREIGN KEY ([SoPhieu]) REFERENCES [PHIEU_MUA_HANG] ([SoPhieu]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [PHIEU_YC_XUAT_KHO] ADD CONSTRAINT [FK_PHIEU_YC_XUAT_KHO_KHO]
	FOREIGN KEY ([MaKho]) REFERENCES [KHO] ([MaKho]) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE [PHIEU_YC_XUAT_KHO] ADD CONSTRAINT [FK_PHIEU_YC_XUAT_KHO_NHAN_VIEN]
	FOREIGN KEY ([MaNV]) REFERENCES [NHAN_VIEN] ([MaNV]) ON DELETE No Action ON UPDATE No Action
;
